### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Blackening999** [polluterofminds/pinata-cli#4]
![pinata_error](https://user-images.githubusercontent.com/2836887/163541911-5e0376a7-9ab1-48c1-a55d-fe6b8ff3460f.jpg)

The folder is big - 35gb. I have paid pinata plan

**Comment by polluterofminds** [comment]
Hey there, 35GB is larger than Pinata supports for a single upload. https://docs.pinata.cloud/rate-limits#upload-size-limits

**Comment by GaiaEich** [comment]
I have the same issue but my folder is only 88.6 MB

**Comment by polluterofminds** [comment]
Hey @GaiaEich can you provide more details: 

- Operating System
- Number of files in folder
- Submarining or uploading normally to IPFS

**Comment by GaiaEich** [comment]
Windows
65'001 files
Uploading normally

**Comment by polluterofminds** [comment]
This appears to be a limitation we occasionally run into during the pinning process. We're exploring solutions for pinning gigantic folders more reliably. But one solution we've discovered is to pin to your own computer using the IPFS desktop app and then using the pin by CID functionality. This article walks you through that: 
https://knowledge.pinata.cloud/en/articles/5508876-how-to-use-ipfs-desktop-with-pinata

While this is something we will continue to improve on the core Pinata API, it's not actually an issue with the CLI tool. The content is successfully making it to the API, but the IPFS process is failing on the server. We have this tracked on the Pinata engineering team and are working on improvements. I'm going to close the issue here.
